DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS User_Followers;
DROP TABLE IF EXISTS Messages;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS UserInfos;
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Auctions;
DROP TABLE IF EXISTS Bidder_Auctions;
